name: Docker Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: dbmscontainers.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t dbmscontainers.azurecr.io/dbms-backend:latest ./backend

    - name: Push Docker Image to ACR
      run: docker push dbmscontainers.azurecr.io/dbms-backend:latest
